### ISSUE TITLE
iOS13対応に伴うREADME修正

### ISSUE THREAD

**Issue by kobayashi-masaya** [NIFCLOUD-mbaas/SwiftPushApp#11]
READMEに変更が生じるであろう箇所
- [概要の対応 iOS version](https://github.com/vfa-namnk/Swift3PushApp/tree/fix_notification_ios_13#%E6%A6%82%E8%A6%81)
- [動作環境](https://github.com/vfa-namnk/Swift3PushApp/tree/fix_notification_ios_13#%E5%8F%82%E8%80%83%E6%A4%9C%E8%A8%BC%E6%B8%88%E3%81%BF%E5%8B%95%E4%BD%9C%E7%92%B0%E5%A2%83)
- [画像サイズが小さい](https://github.com/vfa-namnk/Swift3PushApp/blob/fix_notification_ios_13/readme-img/006.png)
- [PushNotificationのONの仕方が変更になっている](https://github.com/vfa-namnk/Swift3PushApp/tree/fix_notification_ios_13#5-%E5%AE%9F%E6%A9%9F%E3%83%93%E3%83%AB%E3%83%89)

**Comment by natsumo** [comment]
@kobayashi-masaya issue登録ありがとうございます。
動作環境のところ、掲載するにあたり動作確認いただいた環境を教えていただけますか？

**Comment by kobayashi-masaya** [comment]
動作環境は以下の通りです。
```
検証済み動作環境
Mac OS Mojave 10.14.4
Xcode ver.11.2 (11B52)
iPhone 8  iOS 13.3
```
ご確認お願い致します。

**Comment by natsumo** [comment]
@kobayashi-masaya 

すみません。以下確認させてください。

１．
> このサンプルはSwift4.2(iOS12)に対応しています

→こちらは「Swift5(iOS13)」とすればOKでしょうか？

２．以下ソースコードの画像の所について、
https://github.com/NIFCLOUD-mbaas/Swift3PushApp#%E3%83%AD%E3%82%B8%E3%83%83%E3%82%AF

実際のソースコードと差異があるようでした・・・
以下修正案で問題ないかご確認をお願いします。

---

### ロジック

* `AppDelegate.swift` の `didFinishLaunchingWithOptions` メソッド内に、「APNsに対してデバイストークンを要求するコード」を記述しています

```swift
let center = UNUserNotificationCenter.current()
center.requestAuthorization(options: [.alert, .badge, .sound]) {granted, error in
    if error != nil {
        // エラー時の処理
        return
    }
    if granted {
        // デバイストークンの要求
        UIApplication.shared.registerForRemoteNotifications()
    }
}
```

* デバイストークン取得後、 `didRegisterForRemoteNotificationsWithDeviceToken` メソッドが呼ばれ、取得したデバイストークンをニフクラmobile backend 上に保存しています

```swift
// 端末情報を扱うNCMBInstallationのインスタンスを作成
let installation : NCMBInstallation = NCMBInstallation.currentInstallation
// デバイストークンの設定
installation.setDeviceTokenFromData(data: deviceToken)
// 端末情報をデータストアに登録
installation.saveInBackground {result in
    switch result {
        case .success:
            // 端末情報の登録に成功した時の処理
            break
        case let .failure(error):
            // 端末情報の登録に失敗した時の処理
            print(error)
            break
    }
}
```

**Comment by natsumo** [comment]
（メモ）
上記で正しいと仮定してPR作成済み。間違いがあれば修正してマージする。

**Comment by kobayashi-masaya** [comment]
質問ありがとうございます。

１．
> こちらは「Swift5(iOS13)」とすればOKでしょうか？
こちらncmb_swiftがSwift 4.2まで対応と記載してしまっているので、Swift4.2(iOS13)と記載お願いいたします。またncmb_swiftの次回リリース時にSwift5.xに対応できるかチェックし問題無いようであれば、Swiftサンプルのほうも合わせて最新化することにしようと思います。

また補足なのですがSwift 5(Xcode 11.4)以上でも動作するかと思われます。

2.
ほんとうですね。コードが古いものになっていますね。
池田さんの示してくださったコードで問題ないかと思います。

上記の内容で不明な点などございましたらご連絡ください。

**Comment by natsumo** [comment]
@kobayashi-masaya 
確認ありがとうございます。

そうしたら、XcodeやiOSのバージョンについては動作検証端末のところに記載しているので、
ここでは「Swift5系」と記載しておこうと思います。
